services:
  postgres:
    image: postgres:16-alpine
    container_name: lohono-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lohono
      POSTGRES_PASSWORD: lohono
      POSTGRES_DB: lohono
    ports:
      - "5432:5432"
    volumes:
      - lohono-pg:/var/lib/postgresql/data

volumes:
  lohono-pg:
