import type { OpeningHours, PoiCategory, PriceBand, Seasonality } from "@lohono/shared-types";
import { hours, monsoonOff, yearRound } from "./_helpers.js";

export interface SeedPoi {
  name: string;
  category: PoiCategory;
  lat: number;
  lng: number;
  vibeTags: string[];
  priceBand: PriceBand;
  avgDurationMin: number;
  openingHours: OpeningHours;
  seasonality: Seasonality;
  kidFriendly: boolean;
  bookable: boolean;
  conciergeNote: string;
  qualityScore: number;
  bookingUrl?: string | null;
}

// ~40 real North Goa POIs. Coordinates are approximations from public sources.
export const GOA_POIS: SeedPoi[] = [
  // ── Beaches ─────────────────────────────────────────────────────────────
  { name: "Ashwem Beach", category: "beach", lat: 15.6432, lng: 73.7361, vibeTags: ["relax", "calm", "romantic"], priceBand: "$", avgDurationMin: 180, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "Soft sand and shallow water — Ashwem is where you go when Anjuna feels too loud.", qualityScore: 0.92 },
  { name: "Morjim Beach", category: "beach", lat: 15.6316, lng: 73.7327, vibeTags: ["relax", "family"], priceBand: "$", avgDurationMin: 150, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "Wide, uncrowded, and a favourite of the Olive Ridley turtles that nest here from November.", qualityScore: 0.9 },
  { name: "Vagator Beach", category: "beach", lat: 15.5951, lng: 73.7402, vibeTags: ["party", "sunset"], priceBand: "$", avgDurationMin: 150, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: false, bookable: false, conciergeNote: "Cliff-fringed, dramatic, and reliably golden at the last hour of light.", qualityScore: 0.88 },
  { name: "Anjuna Beach", category: "beach", lat: 15.5735, lng: 73.7407, vibeTags: ["party", "iconic"], priceBand: "$", avgDurationMin: 150, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: false, bookable: false, conciergeNote: "The classic. Louder now than in the 70s but still worth the pilgrimage.", qualityScore: 0.82 },
  { name: "Arambol Beach", category: "beach", lat: 15.6874, lng: 73.7031, vibeTags: ["bohemian", "sunset"], priceBand: "$", avgDurationMin: 180, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "Drum circles at dusk, a freshwater lake ten minutes north, and the best sunsets in North Goa.", qualityScore: 0.9 },
  { name: "Mandrem Beach", category: "beach", lat: 15.6613, lng: 73.7222, vibeTags: ["calm", "romantic"], priceBand: "$", avgDurationMin: 150, openingHours: hours.beach(), seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "A tidal creek separates you from the crowds — cross the bamboo bridge and the beach opens up.", qualityScore: 0.93 },

  // ── Restaurants ────────────────────────────────────────────────────────
  { name: "Gunpowder", category: "restaurant", lat: 15.5966, lng: 73.7514, vibeTags: ["foodie", "south-indian"], priceBand: "$$$", avgDurationMin: 90, openingHours: hours.restaurant("mon"), seasonality: yearRound, kidFriendly: true, bookable: true, conciergeNote: "Chettinad and coastal Kerala done properly. Order the crab.", qualityScore: 0.94 },
  { name: "Thalassa", category: "restaurant", lat: 15.6003, lng: 73.7397, vibeTags: ["romantic", "sunset", "greek"], priceBand: "$$$", avgDurationMin: 120, openingHours: hours.restaurant(), seasonality: monsoonOff, kidFriendly: false, bookable: true, conciergeNote: "Book the terrace at 6pm — the sun setting behind the fire dancers is a photo you'll actually keep.", qualityScore: 0.9 },
  { name: "A Reverie", category: "restaurant", lat: 15.5462, lng: 73.7602, vibeTags: ["romantic", "fine-dining"], priceBand: "$$$$", avgDurationMin: 150, openingHours: hours.restaurant(), seasonality: yearRound, kidFriendly: false, bookable: true, conciergeNote: "Long, unhurried, and quietly the best plating on the coast.", qualityScore: 0.96 },
  { name: "Bomra's", category: "restaurant", lat: 15.5497, lng: 73.7601, vibeTags: ["foodie", "burmese"], priceBand: "$$$", avgDurationMin: 90, openingHours: hours.restaurant("sun"), seasonality: yearRound, kidFriendly: true, bookable: true, conciergeNote: "Burmese food you didn't know you needed. The tea-leaf salad is the reason to book.", qualityScore: 0.93 },
  { name: "Vinayak Family Restaurant", category: "restaurant", lat: 15.6289, lng: 73.7501, vibeTags: ["local", "value"], priceBand: "$$", avgDurationMin: 60, openingHours: hours.restaurant(), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Roadside, unpretentious, and the fish thali locals actually eat.", qualityScore: 0.87 },
  { name: "Fisherman's Wharf", category: "restaurant", lat: 15.5518, lng: 73.7590, vibeTags: ["family", "seafood"], priceBand: "$$$", avgDurationMin: 90, openingHours: hours.restaurant(), seasonality: yearRound, kidFriendly: true, bookable: true, conciergeNote: "Riverfront, big menu, dependable — a low-effort win with kids in tow.", qualityScore: 0.82 },
  { name: "Sublime", category: "restaurant", lat: 15.5993, lng: 73.7391, vibeTags: ["romantic", "modern-indian"], priceBand: "$$$$", avgDurationMin: 120, openingHours: hours.restaurant("tue"), seasonality: yearRound, kidFriendly: false, bookable: true, conciergeNote: "Chef Chris Saleem Agha Bee's cooking still surprises — book the tasting menu.", qualityScore: 0.94 },

  // ── Bars ───────────────────────────────────────────────────────────────
  { name: "Antares", category: "bar", lat: 15.5942, lng: 73.7370, vibeTags: ["party", "sunset"], priceBand: "$$$", avgDurationMin: 120, openingHours: hours.bar(), seasonality: monsoonOff, kidFriendly: false, bookable: true, conciergeNote: "Sarjaano Khalid's rooftop overlooking Vagator — golden hour is the reservation to have.", qualityScore: 0.9 },
  { name: "Curlies", category: "bar", lat: 15.5726, lng: 73.7403, vibeTags: ["party", "iconic"], priceBand: "$$", avgDurationMin: 120, openingHours: hours.bar(), seasonality: monsoonOff, kidFriendly: false, bookable: false, conciergeNote: "The oldest beach shack on Anjuna. Loud, laced with nostalgia, still fun after midnight.", qualityScore: 0.75 },
  { name: "Titlie", category: "bar", lat: 15.5977, lng: 73.7458, vibeTags: ["romantic", "cocktails"], priceBand: "$$$", avgDurationMin: 90, openingHours: hours.bar(), seasonality: yearRound, kidFriendly: false, bookable: true, conciergeNote: "Small, thoughtful cocktail bar with a food menu that punches above its size.", qualityScore: 0.9 },

  // ── Heritage / culture ─────────────────────────────────────────────────
  { name: "Basilica of Bom Jesus", category: "heritage", lat: 15.5009, lng: 73.9114, vibeTags: ["cultural", "history"], priceBand: "$", avgDurationMin: 60, openingHours: hours.heritage(), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "The relics of St Francis Xavier and 400 years of Baroque calm.", qualityScore: 0.88 },
  { name: "Se Cathedral", category: "heritage", lat: 15.5013, lng: 73.9116, vibeTags: ["cultural", "history"], priceBand: "$", avgDurationMin: 45, openingHours: hours.heritage(), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "One of Asia's largest churches — walk here after Bom Jesus, they share a plaza.", qualityScore: 0.83 },
  { name: "Chapora Fort", category: "heritage", lat: 15.6055, lng: 73.7350, vibeTags: ["cultural", "sunset", "view"], priceBand: "$", avgDurationMin: 60, openingHours: hours.everyday("07:00", "18:30"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Ruined, sun-baked and famously the fort from *Dil Chahta Hai* — climb up before 5pm.", qualityScore: 0.85 },
  { name: "Fontainhas Latin Quarter", category: "heritage", lat: 15.4987, lng: 73.8341, vibeTags: ["cultural", "walk", "photogenic"], priceBand: "$", avgDurationMin: 90, openingHours: hours.everyday("06:00", "22:00"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Yellow, blue and lime houses on cobbled lanes — go on a Saturday morning.", qualityScore: 0.92 },
  { name: "Reis Magos Fort", category: "heritage", lat: 15.5031, lng: 73.8114, vibeTags: ["cultural", "view"], priceBand: "$", avgDurationMin: 75, openingHours: hours.closedOn("mon", "09:30", "17:30"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Restored to a gallery — quiet, breezy, and a good pit-stop between Panjim and the villa.", qualityScore: 0.86 },
  { name: "Aguada Fort", category: "heritage", lat: 15.4924, lng: 73.7734, vibeTags: ["cultural", "view", "sunset"], priceBand: "$", avgDurationMin: 60, openingHours: hours.everyday("09:00", "18:00"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "The lighthouse is closed but the ramparts and the view along Sinquerim are still worth the climb.", qualityScore: 0.84 },

  // ── Markets ────────────────────────────────────────────────────────────
  { name: "Anjuna Flea Market", category: "market", lat: 15.5751, lng: 73.7385, vibeTags: ["iconic", "shopping"], priceBand: "$$", avgDurationMin: 120, openingHours: { mon: { open: null, close: null, closed: true }, tue: { open: null, close: null, closed: true }, wed: { open: "09:00", close: "18:00", closed: false }, thu: { open: null, close: null, closed: true }, fri: { open: null, close: null, closed: true }, sat: { open: null, close: null, closed: true }, sun: { open: null, close: null, closed: true } }, seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "Wednesdays only. Bargain hard, then reward yourself at the juice stalls behind the far corner.", qualityScore: 0.8 },
  { name: "Mapusa Friday Market", category: "market", lat: 15.5926, lng: 73.8143, vibeTags: ["local", "shopping"], priceBand: "$", avgDurationMin: 90, openingHours: { mon: { open: null, close: null, closed: true }, tue: { open: null, close: null, closed: true }, wed: { open: null, close: null, closed: true }, thu: { open: null, close: null, closed: true }, fri: { open: "07:00", close: "13:00", closed: false }, sat: { open: null, close: null, closed: true }, sun: { open: null, close: null, closed: true } }, seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "The one the locals go to — spices, chorizo, cashew feni. Fridays before eleven.", qualityScore: 0.88 },
  { name: "Saturday Night Market Arpora", category: "market", lat: 15.5773, lng: 73.7532, vibeTags: ["party", "shopping"], priceBand: "$$", avgDurationMin: 150, openingHours: { mon: { open: null, close: null, closed: true }, tue: { open: null, close: null, closed: true }, wed: { open: null, close: null, closed: true }, thu: { open: null, close: null, closed: true }, fri: { open: null, close: null, closed: true }, sat: { open: "18:00", close: "01:00", closed: false }, sun: { open: null, close: null, closed: true } }, seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "Ingo's — live music, food stalls, a hundred vendors under fairy lights. Saturdays after dark.", qualityScore: 0.87 },

  // ── Cafes ──────────────────────────────────────────────────────────────
  { name: "Baba Au Rhum", category: "cafe", lat: 15.5893, lng: 73.7530, vibeTags: ["foodie", "brunch"], priceBand: "$$", avgDurationMin: 75, openingHours: hours.cafe(), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Frenchman-run — pain au chocolat that would hold up in Paris and long, slow brunches.", qualityScore: 0.91 },
  { name: "Artjuna", category: "cafe", lat: 15.5757, lng: 73.7480, vibeTags: ["foodie", "brunch", "boho"], priceBand: "$$", avgDurationMin: 60, openingHours: hours.cafe(), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Middle-Eastern-ish menu, generous salads, and a shop worth twenty minutes on the way out.", qualityScore: 0.89 },
  { name: "Villa Blanche Bistro", category: "cafe", lat: 15.5849, lng: 73.7513, vibeTags: ["brunch", "romantic"], priceBand: "$$", avgDurationMin: 90, openingHours: hours.closedOn("mon", "09:00", "16:00"), seasonality: yearRound, kidFriendly: true, bookable: true, conciergeNote: "A garden brunch that consistently delivers — try the shakshuka.", qualityScore: 0.9 },

  // ── Spas ───────────────────────────────────────────────────────────────
  { name: "Kaya Kalp Spa (Cidade de Goa)", category: "spa", lat: 15.4489, lng: 73.8460, vibeTags: ["wellness", "luxury"], priceBand: "$$$$", avgDurationMin: 90, openingHours: hours.spa(), seasonality: yearRound, kidFriendly: false, bookable: true, conciergeNote: "Ayurvedic, done seriously — book the 90-minute abhyanga.", qualityScore: 0.9 },
  { name: "Sereno Spa (Park Hyatt)", category: "spa", lat: 15.2612, lng: 73.9127, vibeTags: ["wellness", "luxury"], priceBand: "$$$$", avgDurationMin: 120, openingHours: hours.spa(), seasonality: yearRound, kidFriendly: false, bookable: true, conciergeNote: "Long menu but the couples' journey with the sound-bath finish is the one to book.", qualityScore: 0.93 },

  // ── Watersports ─────────────────────────────────────────────────────────
  { name: "Atlantis Watersports Baga", category: "watersport", lat: 15.5527, lng: 73.7517, vibeTags: ["adventure", "family"], priceBand: "$$", avgDurationMin: 120, openingHours: hours.everyday("08:00", "18:00"), seasonality: monsoonOff, kidFriendly: true, bookable: true, conciergeNote: "Ski, banana, parasail bundle — safety kit is inspected properly, which is not universal here.", qualityScore: 0.82 },
  { name: "Barracuda Diving Bogmalo", category: "watersport", lat: 15.3671, lng: 73.8410, vibeTags: ["adventure"], priceBand: "$$$", avgDurationMin: 240, openingHours: hours.everyday("07:00", "18:00"), seasonality: monsoonOff, kidFriendly: false, bookable: true, conciergeNote: "PADI-certified, good boats, and the best chance of visibility in Goan waters.", qualityScore: 0.88 },

  // ── Sunset points ───────────────────────────────────────────────────────
  { name: "Cabo de Rama Cliffs", category: "sunset_point", lat: 15.0834, lng: 73.9298, vibeTags: ["romantic", "view"], priceBand: "$", avgDurationMin: 90, openingHours: hours.everyday("07:00", "18:30"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "Far south — but the drop from the ramparts is worth the 90-minute drive.", qualityScore: 0.9 },
  { name: "Sinquerim Sunset Deck", category: "sunset_point", lat: 15.4972, lng: 73.7681, vibeTags: ["romantic", "view"], priceBand: "$", avgDurationMin: 45, openingHours: hours.everyday("16:00", "20:00"), seasonality: monsoonOff, kidFriendly: true, bookable: false, conciergeNote: "The Aguada headland at 6pm — pack a small blanket.", qualityScore: 0.85 },

  // ── Day trips ──────────────────────────────────────────────────────────
  { name: "Dudhsagar Falls", category: "day_trip", lat: 15.3144, lng: 74.3144, vibeTags: ["adventure", "nature"], priceBand: "$$$", avgDurationMin: 480, openingHours: hours.everyday("06:00", "17:00"), seasonality: { best_months: [7, 8, 9, 10, 11], avoid_months: [3, 4, 5], note: "Best just after the monsoon peaks." }, kidFriendly: true, bookable: true, conciergeNote: "A full day — jeep safari + short trek. Book with a permitted operator, not touts at the gate.", qualityScore: 0.92 },
  { name: "Divar Island by Ferry", category: "day_trip", lat: 15.5158, lng: 73.8843, vibeTags: ["cultural", "slow"], priceBand: "$", avgDurationMin: 300, openingHours: hours.everyday("07:00", "20:00"), seasonality: yearRound, kidFriendly: true, bookable: false, conciergeNote: "A slow half-day: ferry across, cycle the lanes, lunch at a Portuguese-era home.", qualityScore: 0.89 },
  { name: "Chorao Island Bird Sanctuary", category: "day_trip", lat: 15.5153, lng: 73.8676, vibeTags: ["nature", "family"], priceBand: "$$", avgDurationMin: 240, openingHours: hours.everyday("06:00", "17:00"), seasonality: { best_months: [11, 12, 1, 2], avoid_months: [6, 7, 8, 9], note: "Migration window is Nov–Feb." }, kidFriendly: true, bookable: true, conciergeNote: "Salim Ali Bird Sanctuary — go at first light, take the small boat, bring binoculars.", qualityScore: 0.85 },
  { name: "Spice Plantation Lunch (Sahakari)", category: "day_trip", lat: 15.4162, lng: 74.0161, vibeTags: ["cultural", "family"], priceBand: "$$", avgDurationMin: 240, openingHours: hours.everyday("08:00", "16:00"), seasonality: yearRound, kidFriendly: true, bookable: true, conciergeNote: "Guided walk + Konkani thali on banana leaf. Skip the elephants — animal welfare is questionable.", qualityScore: 0.83 },
  { name: "Butterfly Beach by Boat", category: "day_trip", lat: 15.0187, lng: 74.0287, vibeTags: ["adventure", "romantic"], priceBand: "$$$", avgDurationMin: 300, openingHours: hours.everyday("07:00", "17:00"), seasonality: monsoonOff, kidFriendly: true, bookable: true, conciergeNote: "Reachable only by boat from Palolem — book the 8am departure to have it to yourselves.", qualityScore: 0.9 },
];
